### ISSUE TITLE
node-gyp rebuild failure

### ISSUE THREAD

**Issue by woale** [noflo/noflo-gpio#1]
Hi, any idea how to fix this node-gyp rebuild failure ?

pi@3dwpi:~/nfslider$ npm install noflo-gpio --save
npm WARN package.json nfslider@1.0.0 No description
npm WARN package.json nfslider@1.0.0 No repository field.
npm WARN package.json nfslider@1.0.0 No README data
npm WARN package.json noflo-nodejs@0.0.6 No repository field.
/

> node-gpio@0.1.1 install /home/pi/nfslider/node_modules/noflo-gpio/node_modules/node-gpio
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Map '/home/pi/nfslider/node_modules/noflo-gpio/node_modules/node-gpio/build' wordt binnengegaan
  CXX(target) Release/obj.target/gpio/src/node-gpio.o
In file included from ../src/node-gpio.cpp:3:0:
../src/GPIO.h:9:1: error: expected class-name before ‘{’ token
../src/GPIO.h:39:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/GPIO.h:39:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/GPIO.h:41:83: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
../src/GPIO.h:41:101: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
../src/GPIO.h:42:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/GPIO.h:42:64: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/GPIO.h:43:50: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/GPIO.h:43:65: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/GPIO.h:44:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/GPIO.h:44:67: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/GPIO.h:45:50: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/GPIO.h:45:65: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/GPIO.h:46:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/GPIO.h:46:64: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/GPIO.h:47:51: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/GPIO.h:47:66: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
In file included from ../src/node-gpio.cpp:4:0:
../src/PWM.h:26:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/PWM.h:26:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/PWM.h:28:50: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/PWM.h:28:65: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/PWM.h:29:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/PWM.h:29:64: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/PWM.h:30:84: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
../src/PWM.h:30:102: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
../src/PWM.h:31:95: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
../src/PWM.h:31:113: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
../src/PWM.h:32:82: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
../src/PWM.h:32:100: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
../src/PWM.h:33:93: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
../src/PWM.h:33:111: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
In file included from ../src/node-gpio.cpp:5:0:
../src/CapacitiveTouch.h:8:1: error: expected class-name before ‘{’ token
../src/CapacitiveTouch.h:31:48: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/CapacitiveTouch.h:31:63: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/CapacitiveTouch.h:33:49: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/CapacitiveTouch.h:33:64: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/CapacitiveTouch.h:34:50: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/CapacitiveTouch.h:34:65: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/CapacitiveTouch.h:35:59: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/CapacitiveTouch.h:35:74: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/CapacitiveTouch.h:36:54: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/CapacitiveTouch.h:36:69: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
../src/CapacitiveTouch.h:39:87: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
../src/CapacitiveTouch.h:39:105: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
../src/CapacitiveTouch.h:40:98: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
../src/CapacitiveTouch.h:40:116: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
../src/CapacitiveTouch.h:41:89: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
../src/CapacitiveTouch.h:41:107: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
../src/CapacitiveTouch.h:42:100: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
../src/CapacitiveTouch.h:42:118: error: ISO C++ forbids declaration of ‘info’ with no type [-fpermissive]
../src/node-gpio.cpp:7:35: error: ‘Arguments’ in namespace ‘v8’ does not name a type
../src/node-gpio.cpp:7:50: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
/home/pi/.node-gyp/0.12.1/deps/v8/include/v8.h: In function ‘v8::Handlev8::Value Debug(const int&)’:
/home/pi/.node-gyp/0.12.1/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../src/node-gpio.cpp:8:21: error: within this context
../src/node-gpio.cpp:9:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
../src/node-gpio.cpp:10:9: error: ‘ThrowException’ is not a member of ‘v8’
../src/node-gpio.cpp:10:53: error: ‘New’ is not a member of ‘v8::String’
../src/node-gpio.cpp:11:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/node-gpio.cpp:11:42: error: too few arguments to function ‘v8::Handlev8::Primitive v8::Undefined(v8::Isolate_)’
/home/pi/.node-gyp/0.12.1/deps/v8/include/v8.h:305:28: note: declared here
../src/node-gpio.cpp:13:16: error: invalid types ‘const int[int]’ for array subscript
../src/node-gpio.cpp:14:9: error: ‘ThrowException’ is not a member of ‘v8’
../src/node-gpio.cpp:14:53: error: ‘New’ is not a member of ‘v8::String’
../src/node-gpio.cpp:15:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/node-gpio.cpp:15:42: error: too few arguments to function ‘v8::Handlev8::Primitive v8::Undefined(v8::Isolate_)’
/home/pi/.node-gyp/0.12.1/deps/v8/include/v8.h:305:28: note: declared here
../src/node-gpio.cpp:17:43: error: invalid types ‘const int[int]’ for array subscript
../src/node-gpio.cpp:19:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
../src/node-gpio.cpp: In function ‘void init(v8::Handlev8::Object)’:
../src/node-gpio.cpp:26:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
../src/node-gpio.cpp:26:84: error: no matching function for call to ‘v8::FunctionTemplate::New(v8::Handlev8::Value (&)(const int&))’
../src/node-gpio.cpp:26:84: note: candidate is:
/home/pi/.node-gyp/0.12.1/deps/v8/include/v8.h:3455:34: note: static v8::Localv8::FunctionTemplate v8::FunctionTemplate::New(v8::Isolate_, v8::FunctionCallback, v8::Handlev8::Value, v8::Handlev8::Signature, int)
/home/pi/.node-gyp/0.12.1/deps/v8/include/v8.h:3455:34: note:   no known conversion for argument 1 from ‘v8::Handlev8::Value(const int&)’ to ‘v8::Isolate_’
../src/node-gpio.cpp: In function ‘v8::Handlev8::Value Debug(const int&)’:
../src/node-gpio.cpp:20:1: warning: control reaches end of non-void function [-Wreturn-type]
gpio.target.mk:90: recept voor doel 'Release/obj.target/gpio/src/node-gpio.o' is mislukt
make: **\* [Release/obj.target/gpio/src/node-gpio.o] Fout 1
make: Map '/home/pi/nfslider/node_modules/noflo-gpio/node_modules/node-gpio/build' wordt verlaten
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.18.7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/nfslider/node_modules/noflo-gpio/node_modules/node-gpio
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Linux 3.18.7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "noflo-gpio" "--save"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-gpio@0.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-gpio@0.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-gpio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-gpio
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/nfslider/npm-debug.log
pi@3dwpi:~/nfslider$ 

Any help is much appreciated! Thanks, woale.

**Comment by jonnor** [comment]
The library we use `node-gpio` does not seem well maintained, last release 2 years ago.
The `rpio` module, seems much better: https://www.npmjs.com/package/rpio

**Comment by jonnor** [comment]
Other alternatives would be to use some of the JS/Node robotics frameworks, like
https://www.npmjs.com/package/johnny-five or https://www.npmjs.com/package/cylon-gpio - but these have a wider scope, probably too much for this library.
